### ISSUE TITLE
Make it work with Mailgun/Sendgrid

### ISSUE THREAD

**Issue by dangayle** [samdobson/fwdform#1]
Is it possible to modify the script so it can use Mailgun or Sendgrid, in addition to Mandrill?

**Comment by samdobson** [comment]
Hi Dan, it's on my todo list, will get to it some day. In the meantime I'm happy to accept pull requests.

**Comment by rincewind** [comment]
I've added a pull request with SMTP support: #10

**Comment by samdobson** [comment]
Unfortunately never got around to merging this. @rincewind fork is worth checking out if you are comfortable setting up an SMTP server.
