### ISSUE TITLE
Sorry, something went wrong! (Problem with registration)

### ISSUE THREAD

**Issue by RAntonello** [samdobson/fwdform#13]
Registering my email works fine and I get a token, but when I run the test script by subbing in the token it yields the error message "Sorry, something went wrong!".   When I tried modifying the token to see if anything would change, I received the error message "User not found". So fwdform recognizes that my email was registered, but still doesn't work. I don't really have the time to debug this myself, but this seems like a very basic issue, so I might be doing something wrong. Are only certain email accounts  usable? 

EDIT: After looking into this slightly more, I believe it is likely that the recent changes to Mandrill have made fwdform unusable.

**Comment by RAntonello** [comment]
After looking into this slightly more, I believe it is likely that the recent changes to Mandrill have made fwdform unusable.

**Comment by ongerit** [comment]
I am getting a similar issue.

**Comment by bifacil** [comment]
I have been using this service for a long time. It worked great!

However, it seems is not working any more. I am also getting this error message:

> Sorry, something went wrong!

Is this project stil manteined?

**Comment by gomjabar6** [comment]
Same thing going on with me, able to sub a new user but unable to have the system send an email. Also get the error message:

> Sorry, something went wrong!

**Comment by arthurlacoste** [comment]
Same for me :/

**Comment by samdobson** [comment]
Mandrill have killed their free service, see https://github.com/samdobson/fwdform/commit/46254ed10c61a70acf0ba3eb575e44f90d793611
