### ISSUE TITLE
Setup up my own instance

### ISSUE THREAD

**Issue by whosdustin** [samdobson/fwdform#2]
I setup my own instance and seem to be having trouble registering my email and testing it. This is the only way I know how to contact you.

**Edit:** I know nothing about Python and don't know how to debug it. Every time i try to create a new Token through /register instead of coming back with a long string it just says 'Sorry, something went wrong!'. It looks like that is your error handling.

**Comment by ghost** [comment]
Same here and no answer in 2 months. Guess I need to find different solution. It's a cool idea but it makes no sense to dig into all the parts to find the issue myself

EDIT: the error occurs in this line
user = User.query.filter_by(email=request.form['email']).first()
So the question is, is it the db or the code?

EDIT: I removed the code which prevents checking for existing users and it still won't work. So there is sth wrong with the DB connection or how it is used.

This will still fail:
@app.route('/register', methods=['POST'])
def register():
    user = User(request.form['email'])
    db.session.add(user)
    db.session.commit()
    return "Token: {}".format(user.uuid)

**Comment by lilyvelour** [comment]
Did anyone figure anything out here? Also running into the same issue trying to set up.

**Comment by brpaz** [comment]
Same problem here. Any solution?

**Comment by Benjamin-Dobell** [comment]
Also not a Python guy and had the same problem. However, I did manage to piece things together eventually. The issue is that the database & user table needs to be created. I've submitted a pull request (https://github.com/samdobson/fwdform/pull/3) which includes an updated README.

**Comment by samdobson** [comment]
Hopefully this has been clarified now. Thanks @alotaiba for the bugfix and @Benjamin-Dobell for the additional documentation.
