### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by nilsi** [samdobson/fwdform#4]
Getting 405 when trying this out. Its works testing through terminal but not when using the html form.

**Comment by WesleyCharlesBlake** [comment]
This is not a bug. You are getting this error because you have not defined your method for your form.

a form needs and action and method, 

`method="post">`

**Comment by onrea** [comment]
@samdobson
Please update the instruction here: http://samdobson.github.io/fwdform/

It's needed to add `method="post"` to `<form>`

And:

```
Email: <input type="text" name="email"><br>
```

`type="text"` ==>  `type="email"`

**Comment by samdobson** [comment]
Wesley had it, no bug here: you needed to define form method as POST.
