### ISSUE TITLE
"Sorry, Something went wrong"

### ISSUE THREAD

**Issue by milindalvares** [samdobson/fwdform#5]
So I'm having issues with the basic function:

> curl --data "email=my@email.com" https://fwdform.herokuapp.com/register
> token: 95424604-32cf-4da7-8317-945xxx
> curl --data "email=test@me.com&name=person&message=hello" https://fwdform.herokuapp.com/user/95424604-32cf-4da7-8317-945xxx

produces "Sorry, something went wrong!".

**Comment by samdobson** [comment]
Oops! Good catch. Fixed by de992e0.
