### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by icedaq** [samdobson/fwdform#9]
I am trying to use your fwdform instance but I get the following error(in firefox) after submitting the form: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fwdform.herokuapp.com/user/<myToken>. (Reason: CORS request failed).`
The message gets sent but I do not receive any feedback from your script.

I generate the POST request using the following javascript:

``` javascript
$.ajax({
           url: "https://fwdform.herokuapp.com/user/<myToken>",
           type: "POST",
           crossDomain: true,
           data: {
               name: name,
               email: email,
               message: message
           },
           cache: false,
           success: function(){},
           error: function(){},
       })
```

When I look at the headers of my request, I see that the 'Origin' header is set. But in the headers of the response, I do not see anything CORS related. Is it possible that your script does not send the required headers back or is something wrong with my code/how I make the request?

Thanks for your help.

**Comment by samdobson** [comment]
Probably needed to remove crossDomain, but as this repository is being archived, I'm going to close this.
